---
# Install Nginx
- name: NGINX | Install eper-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX | Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start nginx
- name: NGINX | Create general config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: Reload nginx
